### ISSUE TITLE
Hacer un ejemplo para obtener las palabras más similares a una palabra semilla, utilizando embeddings

### ISSUE THREAD

**Issue by miangacu** [pendrag/monge#4]
Se trata de obtener una bolsa de palabras relacionadas, por ejemplo, con la palabra semilla "gripe"

**Comment by sjzafra** [comment]
**Example of use:** python3 get_most_similar_words.py -w gripe -m ./SBW-vectors-300-min5.bin.gz -f binary -n 10
**Output:**
Getting 10 most similar words to the word gripe

Most similar words using cosine similarity between a simple mean of the projection weight vectors of the given words and the vectors for each word in the model
[('aviar', 0.8565480709075928), ('influenza', 0.8387084007263184), ('AHDIGITO', 0.814512312412262), ('pandémica', 0.7719760537147522), ('Gripe', 0.7400607466697693), ('Influenza', 0.7368493676185608), ('pandemia', 0.7282171249389648), ('epidémico', 0.7235727310180664), ('aviaria', 0.7186137437820435), ('varicela', 0.7051491141319275)]

Most similar words using the multiplicative combination objective proposed by Omer Levy and Yoav Goldberg
[('aviar', 0.9282731413841248), ('influenza', 0.9193533062934875), ('AHDIGITO', 0.907255232334137), ('pandémica', 0.8859871625900269), ('Gripe', 0.8700295686721802), ('Influenza', 0.8684238195419312), ('pandemia', 0.8641077280044556), ('epidémico', 0.8617855310440063), ('aviaria', 0.8593060374259949), ('varicela', 0.8525737524032593)]
