### ISSUE TITLE
Traducir los términos semilla y la bolsa de palabras similares al catalán

### ISSUE THREAD

**Issue by miangacu** [pendrag/monge#5]
Utilizando la librería python textblob:
http://textblob.readthedocs.io/en/dev/quickstart.html#translation-and-language-detection

**Comment by fmplaza** [comment]
Finalmente, se ha usado la librería googletrans de python

**Comment by miangacu** [comment]
Perfecto.

Mañana lo probamos a ver.



[image: Universidad de Jaén] <http://www.uja.es/> Miguel Ángel García
Cumbreras
Subdirector de planificación docente de la Escuela Politécnica Superior de
Jaén
magc@ujaen.es

Universidad de Jaén
Escuela Politécnica Superior de Jaén
Edificio A3-Ingeniería y Tecnología, Dep. 112
Campus Las Lagunillas, s/n, 23071 JAÉN | +34 953 212 420
<http://www.ujaen.es/apps/piefirmacorreo4/>

[image: Universidad de Jaén] <http://www.uja.es/>
*********** ADVERTENCIA LEGAL **************
Le informamos, como destinatario de este mensaje, que el correo electrónico
y las comunicaciones por medio de Internet no permiten asegurar ni
garantizar la confidencialidad de los mensajes transmitidos, así como
tampoco su integridad o su correcta recepción, por lo que la Universidad de
Jaén no asume responsabilidad alguna por tales circunstancias. Si no
consintiese en la utilización del correo electrónico o de las
comunicaciones vía Internet le rogamos nos lo comunique y ponga en nuestro
conocimiento de manera inmediata. Este mensaje va dirigido, de manera
exclusiva, a su destinatario y contiene información confidencial y sujeta
al secreto profesional, cuya divulgación no está permitida por la ley. En
caso de haber recibido este mensaje por error, le rogamos que, de forma
inmediata, nos lo comunique por la misma vía respondiendo este mensaje y
proceda a su eliminación, así como a la de cualquier documento adjunto al
mismo. Asimismo, le comunicamos que la distribución, copia o utilización de
este mensaje, o de cualquier documento adjunto al mismo, cualquiera que
fuera su finalidad, están prohibidas por la ley.

2018-01-23 15:03 GMT+01:00 fmplaza <notifications@github.com>:
